### ISSUE TITLE
Error loading when used with Expanded Rocket Payloads Continued

### ISSUE THREAD

**Issue by tigercatt** [nicolas-lang/Factorio.SpaceScienceDelivery#7]
Getting the following error message when trying to load both space science delivery and expanded rocket payloads continued in my mod list, removing either removes the error:

Error loading mods
Failed to load mods: Error while loading recipe prototype "unbox-crate-of-station-science" (recipe): Key "icon" not found in property tree at ROOT.recipe.unbox-crate-of-station-science
Modifications: Space Science Delivery

Mods to be disabled:
- nco-SpaceScienceDelivery(0.0.9)

![image](https://user-images.githubusercontent.com/98614264/151606801-9928fe46-fcf4-44aa-9efd-767dc1054b2c.png)

Other mod found here https://mods.factorio.com/mod/expanded-rocket-payloads-continued

**Comment by nicolas-lang** [comment]
Thanks for the report, I'll have a look.

**Comment by tigercatt** [comment]
If it helps, this is a setup I was using previously. Hadn't touched that save and modlist in a little bit, but it used to work fine maybe a month or two ago.

**Comment by nicolas-lang** [comment]
Yeah, I had to rework a lot of icon related stuff in a previous release - factorio allows various different ways of using icons and if you mess with it you have to implement all possibilities... and somehow I forgot it at one of the locations... 
Should be fixed in 0.0.10, release  will be live in a couple of minutes
